GET localhost:8080/people/all

GET localhost:8080/people/create?name=Андрей

Создал для вас демо проект на spring boot который наглядно показывает как работать с базой. Немного добавлю что база создается в памяти при старте проекта. Вам достаточно скачать проект и запустить его, даее requestPeople.http есть запросы при отправки которых можно получить результат от этого сервера.
